### ISSUE TITLE
Compile Error: "Unsupported Swift architecture"

### ISSUE THREAD

**Issue by levantAJ** [pureprofile/pureprofile-sdk-ios#1]
Hi team, I just created a new project, and start to integrate Pureprofile SDK by CocoaPods

Xcode 14.2, Mac M1 Monterey (12.6)

```
import PureprofileSDK
```

Xcode shows the error: "Unsupported Swift architecture"

<img width="836" alt="Screen Shot 2023-03-03 at 14 27 54" src="https://user-images.githubusercontent.com/6329656/222658629-ef9e3bf9-e8c8-4322-8f8c-c37af5c539cb.png">

Podfile

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestPureprofile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestPureprofile
  pod 'Pureprofile', '1.8.0'

  target 'TestPureprofileTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestPureprofileUITests' do
    # Pods for testing
  end

end

```

The project:

[TestPureprofile.zip](https://github.com/pureprofile/pureprofile-sdk-ios/files/10879279/TestPureprofile.zip)

**Comment by dpapan** [comment]
Hi @levantAJ , on Apple Silicon Macs (M1, M2 etc) the CocoaPod package doesn't support building for the simulator target; you can only build for device (iOS) targets. For developing on Apple Silicon Macs I would suggest to import the SDK using the Swift Package Manager (SPM) which supports both simulator and iOS targets.

**Comment by levantAJ** [comment]
Is there any possibility to convert the framework to normal CocoaPod? @dpapan 
Because our team only uses CocoaPods for managing dependencies, no SPM is supported
And we have to run on simulator for huge unit-tests tasks

**Comment by dpapan** [comment]
Yes, I think it's possible @levantAJ. Early next week I'll release a new version with support for simulator target for the CocoaPod. I'll let you know when it's ready.

**Comment by levantAJ** [comment]
Thanks a lot @dpapan

**Comment by dpapan** [comment]
Hi @levantAJ, v1.8.1 has just been released which adds support for running the SDK with the simulator on Apple Silicon Macs when imported with CocoaPods.

**Comment by levantAJ** [comment]
Hi @dpapan, thanks for the new version, the previous error is gone, but I'm getting a new error `No such module 'PureprofileSDK'`

<img width="794" alt="Screen Shot 2023-03-09 at 09 04 14" src="https://user-images.githubusercontent.com/6329656/223896808-2da39203-dce7-4b85-ba7f-007bd68a59f8.png">

I created a brand new project 👇🏿, and the issue is still there, could you help me create a test project to see if the version is working or not? thanks 

[TestPureprofile.zip](https://github.com/pureprofile/pureprofile-sdk-ios/files/10926961/TestPureprofile.zip)

**Comment by dpapan** [comment]
Hi @levantAJ, let me check that and I'll get back to you

**Comment by dpapan** [comment]
Hi @levantAJ, I wasn't able to reproduce the issue you're having. To be certain that the new version doesn't work only on my Mac, I've asked a colleague to create a sample project and import v1.8.1 with CocoaPods and it worked fine on his Mac too. 
I'd suggest to clean the pods cache, `pod cache clean Pureprofile`, and try installing the pod again. 

Even though your sample project works for me, I'm attaching for reference another sample project that I've created for testing this.

[PPSDKCocoapodsTest.zip](https://github.com/pureprofile/pureprofile-sdk-ios/files/10932613/PPSDKCocoapodsTest.zip)

**Comment by levantAJ** [comment]
It seems the cache problem `pod cache clean Pureprofile` does fix the issue, thanks so much @dpapan for your helping 🙇🏿‍♂️
